### ISSUE TITLE
mod not working, installation error?

### ISSUE THREAD

**Issue by whichtwix** [arukuka/wotmods-discord-rich-presence#13]
mod isnt working, im not sure if i put the files in the right place, or does it not work with 1.15.0.0
![File Explorer 1_9_2022 2_07_04 PM](https://user-images.githubusercontent.com/91138333/148746047-1aa1bfe9-f40d-4cc7-bbf3-5bfbc7c419c1.png)
![File Explorer 1_9_2022 2_07_48 PM](https://user-images.githubusercontent.com/91138333/148746139-4f300157-9a73-4e31-90c4-04c06f4e4039.png)
![File Explorer 1_9_2022 2_07_42 PM](https://user-images.githubusercontent.com/91138333/148746340-df8c436c-6785-4679-88df-4d9e0208a947.png)
0

**Comment by LockBlock-dev** [comment]
See [this](https://github.com/arukuka/wotmods-discord-rich-presence/issues/9) issue..

**Comment by arukuka** [comment]
@whichtwix @LockBlock-dev  
Sorry for the delay in responding.
This mod is now working by updating the build script as described in #14 .
Release page is as follows.

https://github.com/arukuka/wotmods-discord-rich-presence/releases/tag/0.1.5

This mod is currently in review at [the official MOD HUB](https://wgmods.net/).

**Comment by LockBlock-dev** [comment]
The mod is working perfectly, thanks!
